apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Vasary/geron-infrastructure.git
        revision: HEAD
        directories:
          - path: apps/*
