apiVersion: v2
name: redis
description: A Geron helm chart for Redis
type: application
version: 0.1.0
appVersion: "7.0.0"
dependencies:
  - name: redis
    version: 6.0.0
    repository: https://charts.bitnami.com/bitnami
