redis:
  architecture: standalone
  auth:
    enabled: true
    password: "password"

  master:
    persistence:
      enabled: true
      size: 2Gi
      storageClass: "nfs-client"

  replica:
    replicaCount: 1
