redis:
  architecture: standalone
  auth:
    enabled: true
    password: "password"

  master:
    persistence:
      enabled: true
      size: 4Gi
      storageClass: "openebs-hostpath"

  replica:
    replicaCount: 1
