redis:
  architecture: standalone
  auth:
    enabled: true
    password: "password"

  master:
    persistence:
      enabled: true
      size: 2Gi
      storageClass: "openebs-single-replica"

  replica:
    replicaCount: 1
