apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coins-inventory-api
  namespace: argocd
spec:
  project: cfv3
  source:
    repoURL: 'https://github.com/Vasary/geron-infrastructure.git'
    targetRevision: HEAD
    path: services/inventory
  destination:
    server: https://kubernetes.default.svc
    namespace: coins-inventory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=background
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "2m"
