apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: cfv3
  source:
    repoURL: 'https://github.com/Vasary/geron-infrastructure.git'
    targetRevision: HEAD
    path: services/redis
    helm:
      valueFiles:
        - services/redis/values.yaml
  destination:
    server: https://kubernetes.default.svc
