apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cfv3
  namespace: argocd
spec:
  description: App of apps CFV3
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
